{{- if .Values.local_storage.provider }}

{{ $rel_name := .Release.Namespace }}
{{ $crawler_name := .Values.crawler_namespace }}
{{ $storage_class := .Values.volume_storage_class }}
{{ $first_storage := first .Values.storages }}
{{ $main_node_type := .Values.main_node_type }}
{{ $fqdn_suffix := .Values.fqdn_suffix }}

{{- with .Values.local_storage }}

# ensure provider is valid
{{- if not (hasKey .providers .provider) }}
  {{- fail (printf "Error: The 'provider' field was set to '%s', but must be left empty or set to one of the available providers: %s" .provider (join ", " (keys .providers))) }}
{{- end }}

{{ $provider := get .providers .provider }}
---
kind: Secret
apiVersion: v1
metadata:
  name: storage-auth
  namespace: {{ $rel_name }}

type: Opaque
stringData:
  ACCESS_KEY: "{{ $first_storage.access_key }}"
  SECRET_KEY: "{{ $first_storage.secret_key }}"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-storage-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .total_storage }}

  {{- if $storage_class }}
  storageClassName: {{ $storage_class }}
  {{- end }}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-storage
  namespace: {{ $rel_name }}
spec:
  selector:
    matchLabels:
      app: local-storage

  replicas: 1
  template:
    metadata:
      labels:
        app: local-storage

    spec:
      {{- if $main_node_type }}
      nodeSelector:
        nodeType: {{ $main_node_type }}
      {{- end }}

      volumes:
        - name: local-storage
          persistentVolumeClaim:
            claimName: local-storage-pvc

      containers:
        - name: storage
          image: {{ $provider.image }}
          imagePullPolicy: {{ .pull_policy }}
          {{- if $provider.args }}
          args:
          {{- range $provider.args }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}

          env:
            - name: {{ $provider.access_env_var_name }}
              valueFrom:
                secretKeyRef:
                  name: storage-auth
                  key: ACCESS_KEY

            - name: {{ $provider.secret_env_var_name }}
              valueFrom:
                secretKeyRef:
                  name: storage-auth
                  key: SECRET_KEY

          {{- range $key, $value := $provider.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}

          volumeMounts:
            - name: local-storage
              mountPath: /data
              subPath: storage

          resources:
            limits:
              memory: {{ .memory }}

            requests:
              cpu: {{ .cpu }}
              memory: {{ .memory }}

---
apiVersion: v1
kind: Service

metadata:
  namespace: {{ $rel_name }}
  name: local-storage
  labels:
    app: local-storage

spec:
  {{- if .debug_access_port }}
  type: NodePort
  {{- end }}
  selector:
    app: local-storage

  ports:
    - protocol: TCP
      targetPort: {{ $provider.internal_port }}
      port: {{ .service_port }}
      {{- if .debug_access_port }}
      nodePort: {{ .debug_access_port }}
      {{- end }}
      name: storage

---
apiVersion: v1
kind: Service

metadata:
  namespace: {{ $crawler_name }}
  name: local-storage
  labels:
    app: local-storage

spec:
  type: ExternalName
  externalName: "{{ .hostname }}.{{ $rel_name }}{{ $fqdn_suffix }}"

  ports:
    - targetPort: {{ $provider.internal_port }}
      port: {{ .service_port }}


{{- if (and .debug_console_port $provider.debug_console_internal_port) }}
---
apiVersion: v1
kind: Service

metadata:
  namespace: {{ $rel_name }}
  name: local-storage-console
  labels:
    app: local-storage-console

spec:
  type: NodePort
  selector:
    app: local-storage

  ports:
    - protocol: TCP
      port: {{ $provider.debug_console_internal_port }}
      nodePort: {{ .debug_console_port }}
      name: storage-console
{{- end }}

{{- end }}
{{- end }}

