# Local Config
# ------------

# This config is designed for local (non-hosted) use, with either Docker Desktop, minikube or local microk8s.
# With this setup, the cluster should be accessed locally via 'localhost'

# use custom port for local access, default is localhost:30870
# uncomment and change below
# local_service_port: 30870

# Uncomment to set custom organization name
# default_org: "My Local Organization"

# use version specified in values.yaml, uncomment to use :latest release instead
# backend_image: docker.io/webrecorder/browsertrix-backend:latest
# emails_image: docker.io/webrecorder/browsertrix-emails:latest
# frontend_image: docker.io/webrecorder/browsertrix-frontend:latest

# uncomment to enable custom crawler dropdown
# Support for additional crawler release channels
# If more than one channel provided, a dropdown will be shown to users
# 'default' channel must always be included
# crawler_channels:
#   - id: default
#     image: "docker.io/webrecorder/browsertrix-crawler:latest"
#     imagePullPolicy: Always
#
#   # Add, remove, or edit additional crawler release channels for example:
#   - id: custom_version
#     image: "<DOCKER IMAGE>"
#     imagePullPolicy: IfNotPresent  # optional

# overrides to use existing images in local Docker, otherwise will pull from repository
# backend_pull_policy: "Never"
# emails_pull_policy: "Never"
# frontend_pull_policy: "Never"
# crawler_pull_policy: "Never"
# redis_pull_policy: "Never"

# microk8s: if developing locally, can override these to use images from local microk8s repository (on localhost:32000)
# backend_image: "localhost:32000/webrecorder/browsertrix-backend:latest"
# emails_image: "localhost:32000/webrecorder/browsertrix-emails:latest"
# frontend_image: "localhost:32000/webrecorder/browsertrix-frontend:latest"

# optionally, override default mongodb auth, used for all data storage:

# mongo_auth:
#   username: root
#   password: PASSWORD!

# optionally, set these to custom values

# superuser:
#   # set this to enable a superuser admim
#   email: admin@example.com

#   # optional: if not set, automatically generated
#   # change or remove this
#   password: PASSWORD!
