# Resources / Node Types
main_node_type: main

crawler_node_type: crawling
redis_node_type: crawling

crawler_pull_policy: "Always"

crawler_browser_instances: 4

crawler_storage: "220Gi"

# Registry
{% if use_do_registry %}
backend_image: "{{ registry_endpoint }}/webrecorder/browsertrix-backend:{{ image_tag }}"
emails_image: "{{ registry_endpoint }}/webrecorder/browsertrix-emails:{{ image_tag }}"
frontend_image: "{{ registry_endpoint }}/webrecorder/browsertrix-frontend:{{ image_tag }}"
crawler_image: "{{ registry_endpoint }}/webrecorder/browsertrix-crawler:{{ image_tag }}"
{% endif %}

# DB
mongo_local: false

mongo_auth:
  db_url: "{{ db_url }}"

# Storage
minio_local: false

storages:
  - name: "default"
    access_key: "{{ lookup('env', 'DO_AWS_ACCESS_KEY')}}"
    secret_key: "{{ lookup('env', 'DO_AWS_SECRET_KEY')}}"

    endpoint_url: "{{ bucket_endpoint_url }}"


# Domain
ingress:
  host: {{ full_domain }}
  cert_email: {{ cert_email }}
  tls: true


# Signing
{% if enable_signing %}
signer:
  enabled: true
  host: {{ full_signing_domain }}
  cert_email: {{ cert_email }}
  image_pull_policy: "IfNotPresent"
  auth_token: {{ signing_authtoken }}
{% endif %}


# User Auth
superuser:
  email: {{ superuser_email }}
  password: {{ superuser_password }}

registration_enabled: "{{ '1' if registration_enabled else '0' }}"

default_org: "{{ org_name }}"


# Admin Send Email Options
email:
  smtp_port: {{ smtp_port }}
  smtp_host: {{ smtp_host }}
  sender_email: {{ sender_email }}
  password: {{ sender_password }}
  reply_to_email: {{ reply_to_email }}

# Admin Addons
{% if enable_admin_addons %}
addons:
  admin:
    logging: true

btrix-admin-logging:
  logging:
    enabled: true
    dedicatedNode:
      enabled: true
    ingress:
      tls: true
      host: "{{ full_domain }}"
    elasticsearch:
      local: false
    kibana:
      local: false
{% endif %}
