name: Cluster Run (MicroK8s)

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "chart/**"
      - ".github/workflows/microk8s-ci.yaml"
  workflow_dispatch:

env:
  ECHO_SERVER_HOST_URL: http://10.0.1.1:18080

jobs:
  btrix-microk8s-test:
    runs-on: ubuntu-latest
    steps:
      - uses: balchua/microk8s-actions@v0.3.1
        with:
          channel: "1.25/stable"
          addons: '["dns", "helm3", "hostpath-storage", "registry", "host-access"]'
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Wait for registry to be available
        run: curl --retry 20 --retry-delay 10 --retry-connrefused http://localhost:32000/v2/

      - name: Build Backend
        uses: docker/build-push-action@v3
        with:
          context: backend
          push: true
          tags: localhost:32000/webrecorder/browsertrix-backend:latest
          cache-from: type=gha,scope=backend
          cache-to: type=gha,scope=backend,mode=max

      - name: Build Emails
        uses: docker/build-push-action@v3
        with:
          context: emails
          push: true
          tags: localhost:32000/webrecorder/browsertrix-emails:latest
          cache-from: type=gha,scope=emails
          cache-to: type=gha,scope=emails,mode=max

      - name: Build Frontend
        uses: docker/build-push-action@v3
        with:
          context: frontend
          push: true
          tags: localhost:32000/webrecorder/browsertrix-frontend:latest
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,scope=frontend,mode=max

      - name: Create Secret
        run: sudo microk8s kubectl create secret generic btrix-subs-app-secret --from-literal=BTRIX_SUBS_APP_URL=${{ env.ECHO_SERVER_HOST_URL }}/portalUrl

      - name: Start Cluster with Helm
        run: |
          sudo microk8s helm3 upgrade --install -f ./chart/values.yaml -f ./chart/test/test.yaml -f ./chart/test/microk8s-ci.yaml btrix ./chart/

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Python Libs
        run: pip install -r ./backend/test-requirements.txt

      - name: Wait for all pods to be ready
        run: sudo microk8s kubectl wait --for=condition=ready pod --all --timeout=240s

      - name: Run Tests
        run: pytest -vv ./backend/test/test_*.py

      - name: Print Backend Logs
        if: ${{ always() }}
        run: sudo microk8s kubectl logs svc/browsertrix-cloud-backend

      - name: Print Emails Logs
        if: ${{ always() }}
        run: sudo microk8s kubectl logs svc/browsertrix-cloud-emails
