name: Update assigned issues in Webrecorder Projects

on:
  issues:
    types: [assigned]

jobs:
  move-issue-column:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Webrecorder Projects
          column: Todo
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
